/**
 * This file creates literal versions of many of the constants
 * It should be kept in sync with constants.ts
 */

// return codes

type ScreepsReturnCode =
  OK |
  ERR_NOT_OWNER |
  ERR_NO_PATH |
  ERR_BUSY |
  ERR_NOT_FOUND |
  ERR_NOT_ENOUGH_RESOURCES |
  ERR_NOT_ENOUGH_ENERGY |
  ERR_INVALID_TARGET |
  ERR_FULL |
  ERR_NOT_IN_RANGE |
  ERR_INVALID_ARGS |
  ERR_TIRED |
  ERR_NO_BODYPART |
  ERR_NOT_ENOUGH_EXTENSIONS |
  ERR_RCL_NOT_ENOUGH |
  ERR_GCL_NOT_ENOUGH

type OK = 0;
type ERR_NOT_OWNER = -1;
type ERR_NO_PATH = -2;
type ERR_NAME_EXISTS = -3;
type ERR_BUSY = -4;
type ERR_NOT_FOUND = -5;
type ERR_NOT_ENOUGH_RESOURCES = -6;
type ERR_NOT_ENOUGH_ENERGY = -6;
type ERR_INVALID_TARGET = -7;
type ERR_FULL = -8;
type ERR_NOT_IN_RANGE = -9;
type ERR_INVALID_ARGS = -10;
type ERR_TIRED = -11;
type ERR_NO_BODYPART = -12;
type ERR_NOT_ENOUGH_EXTENSIONS = -6;
type ERR_RCL_NOT_ENOUGH = -14;
type ERR_GCL_NOT_ENOUGH = -15;

// Find Constants

type ScreepsFindConstant =
  FIND_EXIT_TOP |
  FIND_EXIT_RIGHT |
  FIND_EXIT_BOTTOM |
  FIND_EXIT_LEFT |
  FIND_EXIT |
  FIND_CREEPS |
  FIND_MY_CREEPS |
  FIND_HOSTILE_CREEPS |
  FIND_SOURCES_ACTIVE |
  FIND_SOURCES |
  FIND_DROPPED_RESOURCES |
  FIND_DROPPED_ENERGY |
  FIND_STRUCTURES |
  FIND_MY_STRUCTURES |
  FIND_HOSTILE_STRUCTURES |
  FIND_FLAGS |
  FIND_CONSTRUCTION_SITES |
  FIND_MY_SPAWNS |
  FIND_HOSTILE_SPAWNS |
  FIND_MY_CONSTRUCTION_SITES |
  FIND_HOSTILE_CONSTRUCTION_SITES |
  FIND_MINERALS |
  FIND_NUKES

type FIND_EXIT_TOP = 1;
type FIND_EXIT_RIGHT = 3;
type FIND_EXIT_BOTTOM = 5;
type FIND_EXIT_LEFT = 7;
type FIND_EXIT = 10;
type FIND_CREEPS = 101;
type FIND_MY_CREEPS = 102;
type FIND_HOSTILE_CREEPS = 103;
type FIND_SOURCES_ACTIVE = 104;
type FIND_SOURCES = 105;
type FIND_DROPPED_RESOURCES = 106;
type FIND_DROPPED_ENERGY = 106; // Yup, it's 106.
type FIND_STRUCTURES = 107;
type FIND_MY_STRUCTURES = 108;
type FIND_HOSTILE_STRUCTURES = 109;
type FIND_FLAGS = 110;
type FIND_CONSTRUCTION_SITES = 111;
type FIND_MY_SPAWNS = 112;
type FIND_HOSTILE_SPAWNS = 113;
type FIND_MY_CONSTRUCTION_SITES = 114;
type FIND_HOSTILE_CONSTRUCTION_SITES = 115;
type FIND_MINERALS = 116;
type FIND_NUKES = 117;
